test: improve credentials management
This adds a new way of loading Playwright testing credentials from a
separate file, aside from the '.env' file.
It will make switching between different environments easier. And AWS
changes will make their management simpler.

diff --git a/.github/workflows/nightly-prod-test-action.yml b/.github/workflows/nightly-prod-test-action.yml
--- a/.github/workflows/nightly-prod-test-action.yml
+++ b/.github/workflows/nightly-prod-test-action.yml
@@ -54,27 +54,14 @@ jobs:
           echo "BASE_URL=$PROD_BASE_URL" >> .env
           echo "PROXY=$RH_PROXY_URL" >> .env
           echo "RH_CLIENT_PROXY=$RH_PROXY_URL" >> .env
-          echo "ADMIN_USERNAME=$PROD_ADMIN_USERNAME" >> .env
-          echo "ADMIN_PASSWORD=$PROD_ADMIN_PASSWORD" >> .env
-          echo "READONLY_USERNAME=$PROD_READONLY_USERNAME" >> .env
-          echo "READONLY_PASSWORD=$PROD_READONLY_PASSWORD" >> .env
-          echo "RHEL_OPERATOR_USERNAME=$PROD_RHEL_OPERATOR_USERNAME" >> .env
-          echo "RHEL_OPERATOR_PASSWORD=$PROD_RHEL_OPERATOR_PASSWORD" >> .env
-          echo "LAYERED_REPO_ACCESS_USERNAME=$PROD_LAYERED_REPO_ACCESS_USERNAME" >> .env
-          echo "LAYERED_REPO_ACCESS_PASSWORD=$PROD_LAYERED_REPO_ACCESS_PASSWORD" >> .env
-          echo "RHEL_ONLY_ACCESS_USERNAME=$PROD_RHEL_ONLY_ACCESS_USERNAME" >> .env
-          echo "RHEL_ONLY_ACCESS_PASSWORD=$PROD_RHEL_ONLY_ACCESS_PASSWORD" >> .env
-          echo "NO_SUBS_USER_USERNAME=$PROD_NO_SUBS_USER_USERNAME" >> .env
-          echo "NO_SUBS_USER_PASSWORD=$PROD_NO_SUBS_USER_PASSWORD" >> .env
-          echo "NO_SUBS_USER_ACTIVATION_KEY=$PROD_NO_SUBS_USER_ACTIVATION_KEY" >> .env
-          echo "NO_SUBS_USER_ORG_ID=$PROD_NO_SUBS_USER_ORG_ID" >> .env
-          echo "ORG_ID_1=$PROD_ORG_ID" >> .env
-          echo "ACTIVATION_KEY_1=$PROD_ACTIVATION_KEY" >> .env
-          echo "LAYERED_REPO_ACCESS_ORG_ID=$PROD_LAYERED_REPO_ACCESS_ORG_ID" >> .env
-          echo "LAYERED_REPO_ACCESS_ACTIVATION_KEY=$PROD_LAYERED_REPO_ACCESS_ACTIVATION_KEY" >> .env
           echo "DOCKER_SOCKET=/var/run/docker.sock" >> .env
-          echo "STABLE_SAM_USERNAME=$PROD_STABLE_SAM_USERNAME" >> .env
-          echo "STABLE_SAM_PASSWORD=$PROD_STABLE_SAM_PASSWORD" >> .env
+
+          if [ -z "$PW_CREDENTIALS" ]; then
+            echo "Error: PW_CREDENTIALS secret is not set."
+            exit 1
+          fi
+
+          printf '%s' "$PW_CREDENTIALS" > creds.json
 
       - name: Run Playwright tests
         run: CURRENTS_PROJECT_ID=jRJFbV CURRENTS_RECORD_KEY=$CURRENTS_RECORD_KEY CURRENTS_CI_BUILD_ID="${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}" yarn playwright test
diff --git a/.github/workflows/playwright-actions.yml b/.github/workflows/playwright-actions.yml
--- a/.github/workflows/playwright-actions.yml
+++ b/.github/workflows/playwright-actions.yml
@@ -29,45 +29,7 @@ jobs:
 
       - name: Create front-end .env file
         run: |
-          # Check if the secrets are set
-          if [ -z "$ADMIN_USERNAME" ]; then
-            echo "Error: ADMIN_USERNAME secret is not set."
-            exit 1
-          fi
-
-          if [ -z "$ADMIN_PASSWORD" ]; then
-            echo "Error: ADMIN_PASSWORD secret is not set."
-            exit 1
-          fi
-
-          if [ -z "$READONLY_USERNAME" ]; then
-            echo "Error: READONLY_USERNAME secret is not set."
-            exit 1
-          fi
-
-          if [ -z "$READONLY_PASSWORD" ]; then
-            echo "Error: READONLY_PASSWORD secret is not set."
-            exit 1
-          fi
-
-          if [ -z "$RHEL_OPERATOR_USERNAME" ]; then
-            echo "Error: RHEL_OPERATOR_USERNAME secret is not set."
-            exit 1
-          fi
-
-          if [ -z "$RHEL_OPERATOR_PASSWORD" ]; then
-            echo "Error: RHEL_OPERATOR_PASSWORD secret is not set."
-            exit 1
-          fi
-
-          # Create the .env file and write the secrets and other variables to it
           {
-            echo "ADMIN_USERNAME=$ADMIN_USERNAME"
-            echo "ADMIN_PASSWORD=$ADMIN_PASSWORD"
-            echo "READONLY_USERNAME=$READONLY_USERNAME"
-            echo "READONLY_PASSWORD=$READONLY_PASSWORD"
-            echo "RHEL_OPERATOR_USERNAME=$RHEL_OPERATOR_USERNAME"
-            echo "RHEL_OPERATOR_PASSWORD=$RHEL_OPERATOR_PASSWORD"
             echo "BASE_URL=https://stage.foo.redhat.com:1337"
             echo "CI=true"
             echo "RBAC=true"
@@ -75,6 +37,13 @@ jobs:
           } >> .env
 
           echo ".env file created successfully."
+
+          if [ -z "$PW_CREDENTIALS" ]; then
+            echo "Error: PW_CREDENTIALS secret is not set."
+            exit 1
+          fi
+
+          printf '%s' "$PW_CREDENTIALS" > creds.json
 
       - name: Get current PR URL
         id: get-pr-url
